models/Confession.php
<?php

namespace app\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "confession".
 *
 * @property int $id
 * @property string $name
 */
class Confession extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */

    public function behaviors()
    {
        return [
            'image' => [
                'class' => 'app\behaviors\ImageBehave',
            ],
        ];
    }
    public $image;

    public static function tableName()
    {
        return 'confession';
    }


    public function getPeople(){
        return $this->hasMany(People::className(),['confess_id'=>'id']);
    }

    public function getPeople6(){
        return $this->hasMany(People::className(),['confess_id'=>'id'])->limit(6);
    }

    public function getObjects(){
        return $this->hasMany(Objects::className(),['confess_id'=>'id'])->where(['status'=>0]);
    }

    public function getObjects4(){
        return $this->hasMany(Objects::className(),['confess_id'=>'id'])->where(['status'=>0])->limit(4);
    }

    public function getTname(){
        if (Lang::getCurrent()->url != 'ru')
            $property = 'name_'.Lang::getCurrent()->url;
        else {
            $property = 'name';
        }
        return $this->{$property};
    }

    public function getShort(){
        if (Lang::getCurrent()->url != 'ru')
            $property = 'short_text_'.Lang::getCurrent()->url;
        else {
            $property = 'short_text';
        }
        return $this->{$property};
    }
    public function getFull(){
        if (Lang::getCurrent()->url != 'ru')
            $property = 'full_text_'.Lang::getCurrent()->url;
        else {
            $property = 'full_text';
        }
        return $this->{$property};
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name','name_kz'], 'required'],
            [['name','short_text','short_text_kz'], 'string', 'max' => 255],
            [['full_text','full_text_kz'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }
    public function afterSave($insert, $changedAttributes){
        parent::afterSave($insert, $changedAttributes);
        $files = UploadedFile::getInstances($this,'image');
        foreach ($files as $file) {
            if (!empty($file) && !$file->hasError) {
                $this->removeImages();
                $filename = 'uploads/' . $file->baseName . '.' . $file->extension;
                $file->saveAs($filename);
                $this->attachImage($filename);
            }
        }
    }

}

models/News.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\web\UploadedFile;

/**
 * This is the model class for table "news".
 *
 * @property int $id
 * @property int $created
 * @property int $updated
 * @property string $preview_text
 * @property string $detail_text
 * @property int $date
 */
class News extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'news';
    }

    const TYPE_NEW = 1;
    const TYPE_VIDEO = 2;

    public $picture;

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created',
                'updatedAtAttribute' => 'updated',
                'value' => time(),
            ],
            'image' => [
                //'class' => 'rico\yii2images\behaviors\ImageBehave',
                'class' => 'app\behaviors\ImageBehave',
            ]

        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title','title_kz'], 'required'],
            [['created', 'updated','type','active'], 'integer'],
            [['detail_text','detail_text_kz'], 'string'],
            [['title','preview_text','preview_text_kz', 'date'], 'string', 'max' => 255],
        ];
    }

    public function getDateformat(){
        return implode('.',array_reverse(explode('.',$this->date)));
    }


    public function getNext() {
        $next = $this->find()->where(['>', 'id', $this->id])->one();
        return $next;
    }

    public function getPrev() {
        $prev = $this->find()->where(['<', 'id', $this->id])->orderBy('id desc')->one();
        return $prev;
    }

    public function getName(){
        if (Lang::getCurrent()->url != 'ru')
            $property = 'title_'.Lang::getCurrent()->url;
        else {
            $property = 'title';
        }
        return $this->{$property};
    }
    public function getDetail(){
        if (Lang::getCurrent()->url != 'ru')
            $property = 'detail_text_'.Lang::getCurrent()->url;
        else {
            $property = 'detail_text';
        }
        return $this->{$property};
    }
    public function getPreview(){
        if (Lang::getCurrent()->url != 'ru')
            $property = 'preview_text_'.Lang::getCurrent()->url;
        else {
            $property = 'preview_text';
        }
        return $this->{$property};
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'created' => 'Created',
            'updated' => 'Updated',
            'preview_text' => 'Preview Text',
            'detail_text' => 'Detail Text',
            'date' => 'Date',
        ];
    }
    public function afterSave($insert, $changedAttributes){
        parent::afterSave($insert, $changedAttributes);

        $file = UploadedFile::getInstance($this, 'picture');
        if (!empty($file) && !$file->hasError) {
            $filename = 'uploads/' . $file->baseName . '.' . $file->extension;
            $file->saveAs($filename);
            $this->removeImages();
            $this->attachImage($filename);
        }
    }
}

models/Objects.php
<?php

namespace app\models;

use app\models\search\People;
use Yii;
use yii\web\UploadedFile;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "objects".
 *
 * @property int $id
 * @property string $name
 * @property string $short_name
 * @property int $confess_id
 * @property string $address
 * @property string $contacts
 * @property int $region_id
 * @property string $description
 * @property string $preview_text
 * @property string $hidden_text
 * @property string $missioners
 * @property string $map
 * @property int $type_id
 * @property int $style_id
 * @property int $icon_id
 */
class Objects extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'objects';
    }

    public function behaviors()
    {
        return [
            'image' => [
                'class' => 'app\behaviors\ImageBehave',
            ],
           /* [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'date_create',
                'updatedAtAttribute' => 'date_update',
                'value' => time(),
            ],*/
           /* 'manyToMany' => [
                'class' => ManyToManyBehavior::className(),
                'relations' => [
                    'tags_ids' => 'tags',
                    'lists_ids' => 'lists',
                    'types_ids' => 'types',
                ],
            ],*/
           /* 'softDeleteBehavior' => [
                'class' => SoftDeleteBehavior::className(),
                'softDeleteAttributeValues' => [
                    'isDeleted' => true
                ],
                'replaceRegularDelete' => true // mutate native `delete()` method
            ],*/
        ];
    }

    public $preview_pic;
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'short_name','name_kz', 'short_name_kz'], 'required'],
            [['confess_id', 'subconfess_id', 'region_id', 'type_id', 'style_id', 'icon_id', 'status'], 'integer'],
            [['description_kz', 'preview_text_kz','description', 'preview_text', 'hidden_text', 'hidden_text_kz', 'missioners'], 'string'],
            [['name', 'short_name', 'address', 'contacts', 'map'], 'string', 'max' => 255],
        ];
    }

    public function getIcon(){
        return $this->hasOne(Icons::className(),['id'=>'icon_id']);
    }

    public function getTname(){
        if (Lang::getCurrent()->url != 'ru')
            $property = 'name_'.Lang::getCurrent()->url;
        else {
            $property = 'name';
        }
        return $this->{$property};
    }  public function getThidden_text(){
        if (Lang::getCurrent()->url != 'ru')
            $property = 'hidden_text_'.Lang::getCurrent()->url;
        else {
            $property = 'hidden_text';
        }
        return $this->{$property};
    }

    public function getTshortname(){
        if (Lang::getCurrent()->url != 'ru')
            $property = 'short_name_'.Lang::getCurrent()->url;
        else {
            $property = 'short_name';
        }
        return $this->{$property};
    }
    public function getDesc(){
        if (Lang::getCurrent()->url != 'ru')
            $property = 'description_'.Lang::getCurrent()->url;
        else {
            $property = 'description';
        }
        return $this->{$property};
    }
    public function getPreview(){
        if (Lang::getCurrent()->url != 'ru')
            $property = 'preview_text_'.Lang::getCurrent()->url;
        else {
            $property = 'preview_text';
        }
        return $this->{$property};
    }



    public function getPeople () {
        return $this->hasMany(People::className(),['object_id'=>'id']);
    }
    public function getConfession (){
        return $this->hasOne(Confession::className(),['id'=>'confess_id']);
    }



    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Полное наименование',
            'short_name' => 'Краткое наименование',
            'confess_id' => 'Конфессия',
            'address' => 'Адрес',
            'contacts' => 'Контактные данные',
            'region_id' => 'Район',
            'description' => 'Подробное описание',
            'description_kz' => 'Подробное описание KZ',
            'preview_text' => 'Краткое описание',
            'preview_text_kz' => 'Краткое описание KZ',
            'hidden_text' => 'Скрытое описание',
            'hidden_text_kz' => 'Скрытое описание KZ',
            'missioners' => 'Миссионеры',
            'map' => 'Координаты на карте',
            'type_id' => 'Тип объекта',
            'status' => 'Скрытый объект',
            'style_id' => 'Стиль объекта',
            'icon_id' => 'Иконка объекта(опционально)',
        ];
    }

    public function afterSave($insert, $changedAttributes){
        parent::afterSave($insert, $changedAttributes);
        $files = UploadedFile::getInstances($this,'preview_pic');
        foreach ($files as $file) {
            if (!empty($file) && !$file->hasError) {
                $filename = 'uploads/' . $file->baseName . '.' . $file->extension;
                $file->saveAs($filename);
                $this->attachImage($filename);
            }
        }
    }
}

controllers/ConfessionController.php
<?php

namespace app\controllers;

use app\models\Confession;
use app\models\Objects;
use app\models\People;
use app\models\search\Subconfess;
use app\models\Types;
use yii\data\Pagination;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;

class ConfessionController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionView($id=null,$conf=null)
    {
        if ($conf) {
            $model = \app\models\Subconfess::findOne($conf);
            $people6 = People::find()->where(['subconfess_id'=>$conf])->limit(6)->all();
            $objects4 = Objects::find()->where(['subconfess_id'=>$conf,'status'=>0])->limit(4)->all();
        } else {
            $model = $this->findModel($id);
            $people6 = $model->people6;
            $objects4 = $model->objects4;
        }
       // echo '<pre>'.print_r($objects4,1).'</pre>'; die;
        return $this->render('view',compact('model','people6','objects4','id','conf'));
    }

    public function actionObjectview($id=null){
        $model = $this->findObject($id);
        return $this->render('objectview',compact('model'));

    }
    public function actionObjects($confess=null,$conf=null,$type=null,$region=null,$q=null){
        /*$model = $this->findModel($confess);

        return $this->render('objects',compact('model'));*/



        $arFilter = [];
        if (\Yii::$app->user->isGuest)
            $arFilter['status'] = 0;

        $confm = null;


        if ($confess) {
            $arFilter['confess_id'] = $confess;
            $confm = Confession::findOne($confess);

        }
        if ($conf) {
            $arFilter['subconfess_id'] = $conf;
        }
        if (\Yii::$app->user->isGuest)
        {
            $aprooved = ArrayHelper::getColumn(Types::find()->where(['active'=>1])->all(),'id');
        }
        else {
            $aprooved = ArrayHelper::getColumn(Types::find()->all(),'id');
        }
        if ($type && in_array($type,$aprooved)) {
            $arFilter['type_id'] = $type;
        } else {
                $arFilter['type_id'] = $aprooved;
        }
        if ($region) {
            $arFilter['region_id'] = $region;
        }


        $query = Objects::find()->where($arFilter)->orderBy('id DESC');

        if ($q) {
            $query->andWhere(
                'name'           .' like "%'.$q.'%" OR '.
                'name_kz'        .' like "%'.$q.'%" OR '.
                'address'        .' like "%'.$q.'%" OR '.
                'contacts'       .' like "%'.$q.'%" OR '.
                'description_kz' .' like "%'.$q.'%" OR '.
                'preview_text_kz'.' like "%'.$q.'%" OR '.
                'description'    .' like "%'.$q.'%" OR '.
                'preview_text'   .' like "%'.$q.'%" '

               );
            //$arFilter['subconfess_id'] = $conf;
        }




       // echo '<pre>'.print_r($query->all(),1).'</pre>';die;

        $countQuery = clone $query;
        $countQuery1 = clone $query;
        $modelraw = $countQuery1->all();

        $pages = new Pagination([
            'totalCount' => $countQuery->count(),
            'defaultPageSize'=>16
        ]);
        $model = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->render('objects', compact('model','pages','confess','conf','region','type','modelraw','confm'));
    }

    public function actionMissionerview($id=null){
        $model = $this->findPeople($id);
        return $this->render('missioner_view',compact('model'));

    }


    public function actionMissioners($confid=null,$conf=null){
        /*$model = $this->findModel($confess);

        return $this->render('objects',compact('model'));*/
        $filter = [];
        if ($conf){
            $filter['subconfess_id']= $conf;
        }

        if ($confid){
            $filter['confess_id'] = $confid;
        }
        $query = People::find()->where($filter)->orderBy('id DESC');
        $countQuery = clone $query;
        $pages = new Pagination([
            'totalCount' => $countQuery->count(),
            'defaultPageSize'=>15
        ]);
        $models = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->render('missioners', [
            'model' => $models,
            'pages' => $pages,
        ]);
    }

    protected function findModel($id)
    {
        if (($model = Confession::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    protected function findObject($id)
    {
        $user_auth = [];
        if (\Yii::$app->user->isGuest)
            $user_auth = ['status'=>0];
        if (($model = Objects::find()->where(array_merge(['id'=>$id],$user_auth))->one()) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    protected function findPeople($id)
    {
        if (($model = People::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }


}

views/confession/index.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\helpers\Url;
$this->title = Yii::t('app','Религия и общество');
?>

<div class="main">
    <br>
    <br>

    <div class="red_h1">
        <div class="h1_rombs">&#9830; &#9830; &#9830; &#9830;</div>
        <?=Yii::t('app','Религия и общество')?>
        <div class="h1_rombs">&#9830; &#9830; &#9830; &#9830;</div>
        <br>

        <div class="black_h2"><?=Yii::t('app','Здесь собраны все официально зарегестрированные конфессии города Алматы')?>
        </div>
    </div>
    <br><br>

    <div class="religions_grey_block_top_icon_outer">
        <div class="religions_icon_inline">
                <div class="religions_icon_block">
                    <img src="/images/icon_hrist.png">


                    <div class="religions_icon_text" ><a style="color:#69c1d3" href="<?=Url::to(['/confession/view','id'=>2])?>"><?=Yii::t('app','ХРИСТИАНСТВО')?></a></div>


                </div>
        </div>
    </div>


    <div class="religions_grey_block_outer">
        <div class="religions_grey_block_inner">


            <div class="religions_grey_block_inner_links">
                Православие<br>
                <a href="<?=Url::to(['/confession/view','id'=>2,'conf'=>1])?>"><?=Yii::t('app','Православная церковь')?></a><br>

            </div>


            <div class="religions_grey_block_inner_links">
                Католицизм<br>
                <a href="<?=Url::to(['/confession/view','id'=>2,'conf'=>2])?>"><?=Yii::t('app','Римско-католическая церковь')?></a><br>
            </div>


            <div class="religions_grey_block_inner_links">
                Протестанизм<br>
                <a href="<?=Url::to(['/confession/view','id'=>2,'conf'=>7])?>"><?=Yii::t('app','Адвентисты Седьмого Дня')?></a><br>
                <a href="<?=Url::to(['/confession/view','id'=>2,'conf'=>10])?>"><?=Yii::t('app','Евангельско-Лютеранская церковь')?></a><br>
                <a href="<?=Url::to(['/confession/view','id'=>2,'conf'=>11])?>"><?=Yii::t('app','Пресвитериане')?></a><br>
                <a href="<?=Url::to(['/confession/view','id'=>2,'conf'=>12])?>"><?=Yii::t('app','Пятидесятники')?></a><br>
                <a href="<?=Url::to(['/confession/view','id'=>2,'conf'=>13])?>"><?=Yii::t('app','Евангельские Христиане-Баптисты')?></a><br>
                <a href="<?=Url::to(['/confession/view','id'=>2,'conf'=>14])?>"><?=Yii::t('app','Методисты')?></a><br>
                <a href="<?=Url::to(['/confession/view','id'=>2,'conf'=>3])?>"><?=Yii::t('app','Новоапостольская церковь')?></a><br>


            </div>


            <div class="religions_grey_block_inner_links">

                <img src="/images/blue_rumb.png" width="15px">
                <a href="<?=Url::to(['/confession/view','id'=>2,'conf'=>4])?>"><?=Yii::t('app','Старообрядческая церковь')?></a><br>

                <img src="/images/blue_rumb.png" width="15px">
                <a href="<?=Url::to(['/confession/view','id'=>2,'conf'=>5])?>"><?=Yii::t('app','Армянская церковь')?></a><br>

            </div>


            <br><br><br>
        </div>
    </div>


    <br>

    <div class="religions_grey_block_bottom_icon_outer">

        <div class="religions_icon_inline">
                <div class="religions_icon_block">
                    <img src="/images/icon_islam.png">


                    <div class="religions_icon_text" ><a style="color:#52ac62; " href="<?=Url::to(['/confession/view','id'=>1])?>">ИСЛАМ</a></div>


                </div>
        </div>


        <div class="religions_icon_inline">
                <div class="religions_icon_block">
                    <img src="/images/icon_buddizm.png">


                    <div class="religions_icon_text" ><a style="color:#e6d80a; " href="<?=Url::to(['/confession/view','id'=>5])?>">БУДДИЗМ</a></div>


                </div>

        </div>

        <?/*<div class="religions_icon_inline">
                <div class="religions_icon_block">
                    <img src="/images/icon_bahai.png">


                    <div class="religions_icon_text" ><a style="color:#8582bc; " href="<?=Url::to(['/confession/view','id'=>3])?>">БАХАИ</a></div>


                </div>
        </div>*/?>

        <div class="religions_icon_inline">
                <div class="religions_icon_block">
                    <img src="/images/icon_iud.png">


                    <div class="religions_icon_text" ><a style="color:#3b3b3b; " href="<?=Url::to(['/confession/view','id'=>6])?>"><?=Yii::t('app','ИУДЕЙСКАЯ <br> РЕЛИГИЯ')?></a></div>


                </div>
        </div>

       <?/* <div class="religions_icon_inline religions_icon_block_mob_fix">
                <div class="religions_icon_block">
                    <img src="/images/icon_krishna.png">


                    <div class="religions_icon_text" ><a style="color:#e8a765; " href="<?=Url::to(['/confession/view','id'=>4])?>"><?=Yii::t('app','ОБЩЕСТВО <br> СОЗНАНИЯ КРИШНЫ')?></a></div>


                </div>
        </div>*/?>

    </div>

    <div class="religions_grey_block_top_icon_outer">
        <div class="religions_icon_inline">
            <div class="religions_icon_block">
                <img src="/images/new.png">


                <div class="religions_icon_text" ><a style="color:#f997c2" href="<?=Url::to(['/confession/view','id'=>7])?>"><?=Yii::t('app','НОВЫЕ РЕЛИГИИ')?></a></div>


            </div>
        </div>
    </div>


    <div class="religions_grey_block_outer">
        <div class="religions_grey_block_inner">

            <div class="religions_grey_block_inner_links">

                <img src="/images/blue_rumb.png" width="15px">
                <a href="<?=Url::to(['/confession/view','id'=>7,'conf'=>6])?>"><?=Yii::t('app','Свидетели Иеговы')?></a><br>

                <img src="/images/blue_rumb.png" width="15px">
                <a href="<?=Url::to(['/confession/view','id'=>7,'conf'=>8])?>"><?=Yii::t('app','Мормоны')?></a><br>

                <img src="/images/blue_rumb.png" width="15px">
                <a href="<?=Url::to(['/confession/view','id'=>7,'conf'=>15])?>"><?=Yii::t('app','Общество Сознания Кришны')?></a><br>

                <img src="/images/blue_rumb.png" width="15px">
                <a href="<?=Url::to(['/confession/view','id'=>7,'conf'=>16])?>"><?=Yii::t('app','Бахаи')?></a><br>




                <img src="/images/blue_rumb.png" width="15px">
                <a href="<?=Url::to(['/confession/view','id'=>7,'conf'=>9])?>"><?=Yii::t('app','Муниты')?></a><br>



            </div>

            <br><br><br>
        </div>
    </div>
</div>
<div class="green_inf_block_outer">
    <div class="white_h1">
        <div class="h1_rombs">&#9830; &#9830; &#9830; &#9830;</div>
        <?=Yii::t('app','Места реализации религиозной литературы и атрибутики')?>
        <div class="h1_rombs">&#9830; &#9830; &#9830; &#9830;</div>
    </div>
    <br><br>
    <div class="blue_but2" style="position: relative; top:0px; font-size: 20px;">
        <a href="<?=Url::to(['/confession/objects','type'=>2])?>"><?=Yii::t('app','Посмотреть список');?></a>
    </div>
</div>

views/confession/view.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Url;
$this->title = $model->name;

?>

<div class="main relig_top_fix" ng-controller="confessview">

    <br><br>

    <div class="relig_header" style="background-image: url('/<?=$model->getImage()->getPath('x185')?>');"></div>
    <br><br><br>
    <?php
        $img = '';
        $color = '';
        switch ($id) {
            case 1:
                $img = '/images/icon_islam.png';
                $color = '#52ac62';
                break;
            case 2:
                $img = '/images/icon_hrist.png';
                $color = '#69c1d3';
                break;
            case 3:
                $img = '/images/icon_bahai.png';
                $color = '#8582bc';
                break;
            case 4:
                $img = '/images/icon_krishna.png';
                $color = '#e8a765';
                break;
            case 5:
                $img = '/images/icon_buddizm.png';
                $color = '#e6d80a';
                break;
            case 6:
                $img = '/images/icon_iud.png';
                $color = '#3b3b3b';
                break;

            case 7:
                $img = '/images/new.png';
                $color = '#f997c2';
                break;
        }

     ?>
    <img src="<?=$img?>" class="relig_icon">

    <div class="relig_desc">

        <div class="green_h1 relig_desc_title" style="color: <?=$color?>"><b><?= $model->tname ?></b></div>
        <br>

        <div class="relig_sub_title"><?= $model->short ?></div>
        <br>




        <div class="relig_hide_desc" ng-show="detail1">
            <?= $model->full ?>
        </div>


        <br>

        <?if ($model->full){?><div class="relig_grey_but" ng-click="detail1=!detail1" id="show_more"><span ng-show="!detail1"><i><?=Yii::t('app','Более детальное описание')?> </i>&or;</span><span ng-show="detail1"><i><?=Yii::t('app','Скрыть')?> </i>&and;</span></div><?}?>
    </div>

    <br><br><br><br>

    <div class="relig_grey_inf_block_outer">

        <div class="blue_h1">
            <div class="h1_rombs">&#9830; &#9830; &#9830; &#9830;</div>
            <?=Yii::t('app','Культовые сооружения');?>
            <div class="h1_rombs">&#9830; &#9830; &#9830; &#9830;</div>
            <br>
        </div>


        <div class="relig_eg_block">
            <br><br>

            <div class="row">

                <? foreach ($objects4 as $item) { ?>
                    <div class="col-xs-6 col-sm-3">
                        <a href="<?=Url::to(['/confession/objectview','id'=>$item->id]) ?>">
                            <div class="relig_eg"
                             style="background-image: url('/<?= $item->getImage()->getPath('150x150') ?>');"></div>
                        </a>
                        <div class="relig_text"><a
                                href="<?=Url::to(['/confession/objectview','id'=>$item->id]) ?>"><?= $item->tname ?></a></div>
                    </div>
                <? } ?>


            </div>
        </div>
    </div>

    <div class="blue_but2" style="position: relative; top:-25px; font-size: 20px;"><a
            href="<?=Url::to(['/confession/objects','confess'=>$id,'conf'=>$conf]);?>"><?=Yii::t('app','Перейти в раздел');?></a></div>


    <div class="white_inf_block_outer">
        <div class="green_h1 relig_desc_title">
            <div class="h1_rombs">&#9830; &#9830; &#9830; &#9830;</div>
            <?=Yii::t('app','Руководители')?>
            <div class="h1_rombs">&#9830; &#9830; &#9830; &#9830;</div>
        </div>

        <div class="relig_missianers_outer"></div>

        <div class="relig_eg_block">
            <br><br>

            <div class="row">

                <? foreach ($people6 as $item) { ?>
                    <div class="col-xs-6 col-sm-2">
                        <a href="<?=Url::to(['/confession/missionerview','id'=> $item->id]) ?>">
                            <div class="relig_missianers_eg"
                                 style="background-image: url('/<?= $item->getImage()->getPath('130x130') ?>');"></div>
                            <div class="relig_text"><?= $item->name ?></div>
                        </a>
                    </div>
                <? } ?>

            </div>

            <br>

        </div>


        <div class="green_but2" style="position: relative; top:0px; font-size: 20px;">
            <a href="<?=Url::to(['/confession/missioners','confid'=>$id,'conf'=>$conf])?>"><?=Yii::t('app','Перейти в раздел');?></a>
        </div>

        <br><br><br>

        <div class="green_inf_block_outer">
            <div class="white_h1">
                <div class="h1_rombs">&#9830; &#9830; &#9830; &#9830;</div>
                <?=Yii::t('app','Миссионеры')?>
                <div class="h1_rombs">&#9830; &#9830; &#9830; &#9830;</div>
            </div>
            <br><br>
            <div class="blue_but2" style="position: relative; top:0px; font-size: 20px;">
                <a href="<?=Url::to(['/pages/missioners'])?>"><?=Yii::t('app','Посмотреть список');?></a>
            </div>
        </div>
        <?/*<div class="green_inf_block_outer">
            <div class="white_h1">
                <div class="h1_rombs">&#9830; &#9830; &#9830; &#9830;</div>
                Стационарные помещения
                <div class="h1_rombs">&#9830; &#9830; &#9830; &#9830;</div>
            </div>
            <br><br>

            <div class="relig_green_block_inner">

                <div class="row">
                    <div class="col-xs-6 col-sm-6 relig_green_block_item"><img src="/images/stat_ic.png">

                        <p>
                            «Джагамбек и С» жауапкерлігі
                            шектеулі сеіріктестігі, «Гулянда» кітаптар үй</p></div>
                    <div class="col-xs-6 col-sm-6 relig_green_block_item"><img src="/images/stat_ic.png">

                        <p>
                            «Джагамбек и С» жауапкерлігі
                            шектеулі сеіріктестігі, «Гулянда» кітаптар үй</p></div>
                    <div class="col-xs-6 col-sm-6 relig_green_block_item"><img src="/images/stat_ic.png">

                        <p>
                            «Джагамбек и С» жауапкерлігі
                            шектеулі сеіріктестігі, «Гулянда» кітаптар үй</p></div>
                    <div class="col-xs-6 col-sm-6 relig_green_block_item"><img src="/images/stat_ic.png">

                        <p>
                            «Джагамбек и С» жауапкерлігі
                            шектеулі сеіріктестігі, «Гулянда» кітаптар үй</p></div>
                </div>

            </div>
        </div>*/?>


    </div>


</div>